package com.nightonke.saver.util;

import com.nightonke.saver.R;

/**
 * Created by hushujun on 2018/1/28.
 */

public class Constances {
    public static int[] WEEKDAY_SHORT_START_ON_MONDAY = {
            0,
            R.string.monday_short,
            R.string.tuesday_short,
            R.string.wednesday_short,
            R.string.thursday_short,
            R.string.friday_short,
            R.string.saturday_short,
            R.string.sunday_short
    };
    public static int[] WEEKDAY_SHORT_START_ON_SUNDAY = {
            0,
            R.string.sunday_short,
            R.string.monday_short,
            R.string.tuesday_short,
            R.string.wednesday_short,
            R.string.thursday_short,
            R.string.friday_short,
            R.string.saturday_short
    };
    public static int[] WEEKDAY_START_ON_MONDAY = {
            0,
            R.string.monday,
            R.string.tuesday,
            R.string.wednesday,
            R.string.thursday,
            R.string.friday,
            R.string.saturday,
            R.string.sunday
    };
    public static int[] WEEKDAY_START_ON_SUNDAY = {
            0,
            R.string.sunday,
            R.string.monday,
            R.string.tuesday,
            R.string.wednesday,
            R.string.thursday,
            R.string.friday,
            R.string.saturday
    };
    public static String[] FLOATINGLABELS = {
            "",
            "",
            "十",
            "百",
            "千",
            "万",
            "十万",
            "百万",
            "千万",
            "亿",
            "十亿"};
    public static String[] BUTTONS = {
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "D",
            "0",
            "Y"
    };
    public static int[] TODAY_VIEW_EMPTY_TIP = {
            R.string.today_empty,
            R.string.yesterday_empty,
            R.string.this_week_empty,
            R.string.last_week_empty,
            R.string.this_month_empty,
            R.string.last_month_empty,
            R.string.this_year_empty,
            R.string.last_year_empty
    };
    public static int[] MONTHS_SHORT = {0,
            R.string.january_short,
            R.string.february_short,
            R.string.march_short,
            R.string.april_short,
            R.string.may_short,
            R.string.june_short,
            R.string.july_short,
            R.string.august_short,
            R.string.september_short,
            R.string.october_short,
            R.string.november_short,
            R.string.december_short
    };
    public static int[] MONTHS = {
            0,
            R.string.january,
            R.string.february,
            R.string.march,
            R.string.april,
            R.string.may,
            R.string.june,
            R.string.july,
            R.string.august,
            R.string.september,
            R.string.october,
            R.string.november,
            R.string.december
    };
    public static int TODAY_VIEW_TITLE[] = {
            R.string.today_view_today,
            R.string.today_view_yesterday,
            R.string.today_view_this_week,
            R.string.today_view_last_week,
            R.string.today_view_this_month,
            R.string.today_view_last_month,
            R.string.today_view_this_year,
            R.string.today_view_last_year
    };
    public static int[] TAG_ICON = {
            R.mipmap.sum_pie_icon,
            R.mipmap.sum_histogram_icon,
            R.mipmap.meal_icon,
            R.mipmap.closet_icon,
            R.mipmap.home_icon,
            R.mipmap.traffic_icon,
            R.mipmap.vehicle_maintenance_icon,
            R.mipmap.book_icon,
            R.mipmap.hobby_icon,
            R.mipmap.internet_icon,
            R.mipmap.friend_icon,
            R.mipmap.education_icon,
            R.mipmap.entertainment_icon,
            R.mipmap.medical_icon,
            R.mipmap.insurance_icon,
            R.mipmap.donation_icon,
            R.mipmap.sport_icon,
            R.mipmap.snack_icon,
            R.mipmap.music_icon,
            R.mipmap.fund_icon,
            R.mipmap.drink_icon,
            R.mipmap.fruit_icon,
            R.mipmap.film_icon,
            R.mipmap.baby_icon,
            R.mipmap.partner_icon,
            R.mipmap.housing_loan_icon,
            R.mipmap.pet_icon,
            R.mipmap.telephone_bill_icon,
            R.mipmap.travel_icon,
            R.mipmap.lunch_icon,
            R.mipmap.breakfast_icon,
            R.mipmap.midnight_snack_icon
    };
    public static int[] TAG_COLOR = {
            R.color.my_blue,
            R.color.sum_header_pie,
            R.color.sum_header_histogram,
            R.color.meal_header,
            R.color.closet_header,
            R.color.home_header,
            R.color.traffic_header,
            R.color.vehicle_maintenance_header,
            R.color.book_header,
            R.color.hobby_header,
            R.color.internet_header,
            R.color.friend_header,
            R.color.education_header,
            R.color.entertainment_header,
            R.color.medical_header,
            R.color.insurance_header,
            R.color.donation_header,
            R.color.sport_header,
            R.color.snack_header,
            R.color.music_header,
            R.color.fund_header,
            R.color.drink_header,
            R.color.fruit_header,
            R.color.film_header,
            R.color.baby_header,
            R.color.partner_header,
            R.color.housing_loan_header,
            R.color.pet_header,
            R.color.telephone_bill_header,
            R.color.travel_header,
            R.color.lunch_header,
            R.color.breakfast_header,
            R.color.midnight_snack_header
    };
    public static int[] TAG_SNACK = {
            R.drawable.snackbar_shape_undo,
            R.drawable.snackbar_shape_sum_pie,
            R.drawable.snackbar_shape_sum_histogram,
            R.drawable.snackbar_shape_meal,
            R.drawable.snackbar_shape_closet,
            R.drawable.snackbar_shape_home,
            R.drawable.snackbar_shape_traffic,
            R.drawable.snackbar_shape_vehicle_maintenance,
            R.drawable.snackbar_shape_book,
            R.drawable.snackbar_shape_hobby,
            R.drawable.snackbar_shape_internet,
            R.drawable.snackbar_shape_friend,
            R.drawable.snackbar_shape_education,
            R.drawable.snackbar_shape_entertainment,
            R.drawable.snackbar_shape_medical,
            R.drawable.snackbar_shape_insurance,
            R.drawable.snackbar_shape_donation,
            R.drawable.snackbar_shape_sport,
            R.drawable.snackbar_shape_snack,
            R.drawable.snackbar_shape_music,
            R.drawable.snackbar_shape_fund,
            R.drawable.snackbar_shape_drink,
            R.drawable.snackbar_shape_fruit,
            R.drawable.snackbar_shape_film,
            R.drawable.snackbar_shape_baby,
            R.drawable.snackbar_shape_partner,
            R.drawable.snackbar_shape_housing_loan,
            R.drawable.snackbar_shape_pet,
            R.drawable.snackbar_shape_telephone_bill,
            R.drawable.snackbar_shape_travel,
            R.drawable.snackbar_shape_lunch,
            R.drawable.snackbar_shape_breakfast,
            R.drawable.snackbar_shape_midnight_snack
    };
    public static int[] TAG_NAME = {
            R.string.tag_sum_pie,
            R.string.tag_sum_histogram,
            R.string.tag_meal,
            R.string.tag_closet,
            R.string.tag_home,
            R.string.tag_traffic,
            R.string.tag_vehicle_maintenance,
            R.string.tag_book,
            R.string.tag_hobby,
            R.string.tag_internet,
            R.string.tag_friend,
            R.string.tag_education,
            R.string.tag_entertainment,
            R.string.tag_medical,
            R.string.tag_insurance,
            R.string.tag_donation,
            R.string.tag_sport,
            R.string.tag_snack,
            R.string.tag_music,
            R.string.tag_fund,
            R.string.tag_drink,
            R.string.tag_fruit,
            R.string.tag_film,
            R.string.tag_baby,
            R.string.tag_partner,
            R.string.tag_housing_loan,
            R.string.tag_pet,
            R.string.tag_telephone_bill,
            R.string.tag_travel,
            R.string.tag_lunch,
            R.string.tag_breakfast,
            R.string.tag_midnight_snack
    };


    public static int[] TAG_DRAWABLE = {
            R.mipmap.transparent
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_histogram,
//            R.drawable.meal_header,
//            R.drawable.closet_header,
//            R.drawable.home_header,
//            R.drawable.traffic_header,
//            R.drawable.vehicle_maintenance_header,
//            R.drawable.book_header,
//            R.drawable.hobby_header,
//            R.drawable.internet_header,
//            R.drawable.friend_header,
//            R.drawable.education_header,
//            R.drawable.entertainment_header,
//            R.drawable.medical_header,
//            R.drawable.insurance_header,
//            R.drawable.donation_header,
//            R.drawable.sport_header,
//            R.drawable.snack_header,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie,
//            R.drawable.sum_header_pie
    };
    public static String[] TAG_HEADER_URL = {
            "http://file.bmob.cn/M02/5A/B5/oYYBAFajMcmAWxDmAAAAX54YFR4292.png",
            "http://file.bmob.cn/M02/5A/B6/oYYBAFajMguAMEjaAACp5TYCw2c161.jpg",
            "http://file.bmob.cn/M02/5A/B7/oYYBAFajMjeAUJ6bAACp5TYCw2c909.jpg",
            "http://file.bmob.cn/M02/5A/B9/oYYBAFajMsCASQSTAAST9c5hnKk541.jpg",
            "http://file.bmob.cn/M02/5A/B9/oYYBAFajMt6ACKvpAAFCadMFDZ0001.jpg",
            "http://file.bmob.cn/M02/5A/BA/oYYBAFajMxaAcCHVAAFMn10yiSc776.jpg",
            "http://file.bmob.cn/M02/5A/BB/oYYBAFajM0WAeSXuAAPMSTPknmg198.jpg",
            "http://file.bmob.cn/M02/5A/BB/oYYBAFajM2uAF2dAAAERt2oghvQ131.jpg",
            "http://file.bmob.cn/M02/5A/BD/oYYBAFajM9mAfvhbAAEAaJskdeI618.jpg",
            "http://file.bmob.cn/M02/5A/BE/oYYBAFajM_GAY_sdAAIiUMzp8aA126.jpg",
            "http://file.bmob.cn/M02/5A/BF/oYYBAFajNBCAfPCYAAIXneirgI8186.jpg",
            "http://file.bmob.cn/M02/5A/C0/oYYBAFajNEuAdQRXAAEeDe0Ytew460.jpg",
            "http://file.bmob.cn/M02/5A/C1/oYYBAFajNGeAHKBYAACR7VAH6tY388.jpg",
            "http://file.bmob.cn/M02/5A/C4/oYYBAFajNOOANYPbAAIMih4I730340.jpg",
            "http://file.bmob.cn/M02/5A/C4/oYYBAFajNP6AREhrAAFRYvfSI1o564.jpg",
            "http://file.bmob.cn/M02/5A/C5/oYYBAFajNRyASQs4AABNrzBmPsU695.jpg",
            "http://file.bmob.cn/M02/5A/C5/oYYBAFajNTCAZJWYAACFnWVbblw284.jpg",
            "http://file.bmob.cn/M02/5A/C6/oYYBAFajNUaACmmCAACd5x8slZY981.jpg",
            "http://file.bmob.cn/M02/5A/C6/oYYBAFajNWKALgknAAHaJgXlKLI169.jpg",
            "http://file.bmob.cn/M02/5A/C7/oYYBAFajNZyAVA0mAAX6uqgz5os812.png",
            "http://file.bmob.cn/M02/5A/CC/oYYBAFajNoeAWF96AAYHTWlvWA8779.png",
            "http://file.bmob.cn/M02/5A/D0/oYYBAFajN4uAcFDhAAbKaer4urk522.png",
            "http://file.bmob.cn/M02/5A/D3/oYYBAFajODSAe5iEAAgDnDRtjG0045.png",
            "http://file.bmob.cn/M02/5A/D6/oYYBAFajOh6AH4ZKAANQpB8MUBQ569.png",
            "http://file.bmob.cn/M02/5A/D6/oYYBAFajOmSAZHFRAAbpe8mI4v0254.png",
            "http://file.bmob.cn/M02/5A/D7/oYYBAFajOpWAKl8gAAZ8d8Z0BAM967.png",
            "http://file.bmob.cn/M02/5A/D7/oYYBAFajOr-Aapj2AAaQOo6Zvzs039.png",
            "http://file.bmob.cn/M02/5A/D8/oYYBAFajOv2ANQlZAAg-CYhjjLQ254.png",
            "http://file.bmob.cn/M02/5A/D9/oYYBAFajOyyAaEqvAAavKIaVqfs654.png",
            "http://file.bmob.cn/M02/5A/DA/oYYBAFajO3WAMt9LAAdYtJz1cCE193.png",
            "http://file.bmob.cn/M02/5A/E1/oYYBAFajPwqAAVQaAAd1j6hRHZw363.png",
            "http://file.bmob.cn/M02/5A/E9/oYYBAFajQruAdJYeAAd3DzoZwNk311.png",
            "http://file.bmob.cn/M02/5A/F4/oYYBAFajRpiAAczeAAgXftIUsqk135.png"
    };
    public static int[] DRAWER_TOP_URL = {
            R.mipmap.material_design_0,
            R.mipmap.material_design_1,
            R.mipmap.material_design_2,
            R.mipmap.material_design_3,
            R.mipmap.material_design_4
    };

    protected static String[] Colors = {"#F44336",
            "#E91E63",
            "#9C27B0",
            "#673AB7",
            "#3F51B5",
            "#2196F3",
            "#03A9F4",
            "#00BCD4",
            "#009688",
            "#4CAF50",
            "#8BC34A",
            "#CDDC39",
            "#FFEB3B",
            "#FFC107",
            "#FF9800",
            "#FF5722",
            "#795548",
            "#9E9E9E",
            "#607D8B"};
}
